;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Gauge",DevComment="pour les jauges de vie, mana, etc...")
+GameplayTagList=(Tag="Gauge.Health",DevComment="")
+GameplayTagList=(Tag="Gauge.Poise",DevComment="")
+GameplayTagList=(Tag="Gauge.Stamina",DevComment="")
+GameplayTagList=(Tag="TestEvent",DevComment="")

